const { db } = require('../firebase');  // Assuming firebase.js exports the initialized Firestore instance

// Service to create a payment record in Firestore
async function createPaymentService(userId, amount, paymentMethod, status) {
  try {
    // Add a new payment document to the 'payments' collection
    const paymentRef = db.collection('payments').doc();  // Creates a new document with a generated ID

    const paymentData = {
      userId,
      amount,
      paymentMethod,
      status,
      paymentDate: new Date().toISOString(),  // Timestamp of payment
    };

    // Set the data to Firestore document
    await paymentRef.set(paymentData);

    // Return the payment data including the generated document ID
    return {
      id: paymentRef.id,  // Document ID generated by Firestore
      ...paymentData,
    };
  } catch (err) {
    throw new Error(`Error creating payment record: ${err.message}`);
  }
}

module.exports = {
  createPaymentService,
};